### PR TITLE
npm audit fix: bump jspdf to 2.3.1

### PR DESCRIPTION
**Pull request by ptanaji-cb**
```
➜  html2pdf.js git:(security-audit-fix) ✗ npm audit

                       === npm audit security report ===

found 0 vulnerabilities
 in 462 scanned packages
```

### CODE REVIEW

**Comment by ptanaji-cb** [comment]
@eKoopmans could we get this in? thanks!

**Comment by ptanaji-cb** [comment]
@eKoopmans @oschwede @drbeat @ovvn Could anyone of you please help prioritize this?

**Comment by eKoopmans** [comment]
Hi @ptanaji-cb , agreed this should be high priority. This is a change in major version for jsPDF, so I'll need a bit of testing before I'm confident that this doesn't break anything.

**Comment by shalinirp** [comment]
Is there any status on this? As still getting the security issue for html2pdf.js

Screenshot 2021-05-17 at 2 11 56 PM

**Comment by Hawxy** [comment]
@eKoopmans Any chance of getting this merged in and a pre-release published? It'd allow for easier testing and resolve the security problems for those with auditing requirements.

**Comment by samputer** [comment]
+1 on this please. It's causing `npm audit` high severity alerts. Happy to help.

**Comment by eKoopmans** [comment]
Hi, I'm actively working on this. It's unfortunately not an easy fix - changes in jsPDF 2.0.0+ are directly incompatible with the way html2pdf.js is built/bundled. It looks like it will be impossible to continue using Rollup.

My next step is to switch to Webpack, if everything goes smoothly I'm hoping to have a fix merged in the next week, maybe two.

**Comment by samputer** [comment]
Thanks @eKoopmans, really appreciate you taking the time for this.

**Comment by ptanaji-cb** [comment]
Hi @eKoopmans , The severity of jspdf dependency has risen to "High".  Any update on this?

```
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ High          │ Regular Expression Denial of Service (ReDoS)                 │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ jspdf                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Patched in    │ >=2.3.1                                                      │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ html2pdf.js                                                  │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ html2pdf.js > jspdf                                          │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://npmjs.com/advisories/1709                            │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

**Comment by eKoopmans** [comment]
Hi everyone, v0.10.0 is now released with all security audits patched. You can access it by updating your dependencies to `"html2pdf.js": "^0.10.0"` - since [the caret locks to a minor version for 0.x releases](https://github.com/npm/node-semver#caret-ranges-123-025-004).

**Comment by ptanaji-cb** [comment]
Awesome! thanks a lot @eKoopmans !

**Pull request closed without merging**
