### PR TITLE
containerCSS backgroundColor: 'transparent'

### PR DESCRIPTION
**Pull request by kakugiki**
A white backgroundColor overwrites the backgroundColor of html2canvas. changed to transparent and added an opt.backgroundColor as well (optional)

### CODE REVIEW

**Comment by kakugiki** [comment]
this may fix issue #133 and #182.

**Comment by hakimio** [comment]
Does setting it to transparent reduce the generated PDF size?

**Comment by kakugiki** [comment]
@hakimio Looks like changing from white to transparent doesn't reduce the file size. I mainly used window.open to view the PDF file, so I might missed something.

**Comment by eKoopmans** [comment]
Hi @kakugiki, thanks for the PR! In fact I'm getting rid of the "container" element entirely, which should be an effective fix for this problem and others. You can see the proposed fix here:

[html2pdf.js/bugfix/clone-nodes-BUILD](/eKoopmans/html2pdf.js/tree/bugfix/clone-nodes-BUILD)

I'm busy working on unit tests for all of html2pdf.js, so I can make sure I'm not breaking things each time I try to fix them. I'll keep you posted!

**Pull request closed without merging**
