### PR TITLE
Fix/sandbox promises

### LINKED ISSUE #220: Not working when newrelic is installed
In my my react app i am trying to generate pdf by doing these
```
html2pdf(HTML_ELEMENT);
```

```
html2pdf().from(HTML_ELEMENT).set({
    margin: 0,
    filename: 'pricing-report.pdf',
    image: { type: 'jpeg', quality: 1 },
    html2canvas: {
        useCORS: true,
        scale: 2,
    },
    jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
})
```

```
html2pdf(HTML_ELEMENT, {
    margin: 0,
    filename: 'pricing-report.pdf',
    image: { type: 'jpeg', quality: 1 },
    html2canvas: {
        useCORS: true,
        scale: 2,
    },
    jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' }
})
```
but every time it return same error
```
Uncaught TypeError: Method Promise.prototype.then called on incompatible receiver #<Promise>
```

If i remove newrelic code it works fine. Looks like newrelic is overwriting `promise.prototype.then`

Is there any way to avoid this problem?

### PR DESCRIPTION
**Pull request by oschwede**
Fixes #220.

Two questions:

- Should built dist-files be included into this PR?
- Is the rollup-config ok? Or should `es6-promise` be included because its an external, non-bundled dependency?

### CODE REVIEW

**Comment by hakimio** [comment]
The promise polyfill should be completely optional and shouldn't be bundled with html2pdf.js at all.

**Comment by eKoopmans** [comment]
Hi @oschwede, thanks for the PR! No need to rebuild dist, we'll do that at the next release.

The details of `external` and `globals` are always tricky. You've done right to remove it from `external` altogether, but I think we should now add it to *every* `globals` field (see [the docs](https://rollupjs.org/guide/en/#outputglobals)):

```js
globals: {
  ...
  'es6-promise': 'es6promise'
}
```

Other than that, looks great! Thanks again, I'll merge it when that's done.

@hakimio html2pdf.js relies on specific Promise behaviour, and there have been problems with people using non-standard Promise libraries. As a result, it's necessary to sandbox a "known" Promise library internally. It unfortunately makes the filesize larger, but should make it more stable.

**Comment by oschwede** [comment]
I've added es6-promise to the globals sections.

**Comment by eKoopmans** [comment]
Looks great, thanks!

**Pull request merged**
